import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SkillMe | Start Learning Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.imgContainer}>

        </div>

          <h1 className={styles.title} >SKILLME</h1>
      </header>
      <div className={styles.container}>
        <div className={styles.infoContainer}>
          <h2 className={styles.subTitle}>Empowering Minds. Your Gateway to Online Learning.</h2>
          <Link href='/login'> 
          <button className={styles.getStartedBtn}>
            Get Started
          </button>
          </Link>
          
        </div>
        <div className={styles.bannerContainer}>
          <Image className={styles.bannerImg} src="/assets/Software-Developer.svg" width={400} height={350}>

          </Image>
        </div>
      </div>

    </>
  )
}


